version: '2.2'

services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: messenger_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - prom_data:/opt/bitnami/prometheus/data

volumes:
  pg_data:
  prom_data:
