# Generated by Django 4.2.9 on 2024-02-01 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatmembership',
            unique_together={('chat_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user_id', 'contact_id')},
        ),
    ]
